# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Sphinx LuaLaTeX sample project'
copyright = '2019, Yoshi Yamaguchi'
author = 'Yoshi Yamaguchi'

# The full version, including alpha/beta/rc tags
release = '0.1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.blockdiag',
    'sphinxcontrib.seqdiag',
    'sphinxcontrib.actdiag',
    'sphinxcontrib.nwdiag',
    'sphinxcontrib.rackdiag',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# LuaLaTeX setting
latex_engine = 'lualatex'
latex_docclass = {
    'manual': 'ltjsbook'
}
latex_toplevel_sectioning = 'chapter'
latex_show_urls = 'inline'
latex_elements = {
    'papersize': 'a4paper',
    'figure_align': 'H',
    'extraclassoptions': r"autodetect-engine, dvipdfmx-if-dvi, base=11pt, ja=standard, openany",
    'fontpkg': r'''
\usepackage[default, regular, bold]{sourcesanspro}
\usepackage[default, regular, bold]{sourceserifpro}
\setmonofont{CMU Typewriter Text}
\usepackage[sourcehan-jp, nfssonly, deluxe]{luatexja-preset}
''',
    'fncychap': r'''
\usepackage[Bjornstrup]{fncychap}
\ChNameVar{\Large\headfont}
\ChTitleVar{\bfseries\Large\mcfamily\rmfamily}
\makeatletter
\renewcommand{\DOCH}{%
  \settoheight{\myhi}{\CTV\FmTi{Test}}
  \setlength{\py}{\baselineskip}
  \addtolength{\py}{\RW}
  \addtolength{\py}{\myhi}
  \setlength{\pyy}{\py}
  \addtolength{\pyy}{-1\RW}
  \raggedright
  \CNV\FmN{\@chapapp}\space\CNoV\thechapter\CNV\FmN{\@chappos}
  \hskip 3pt\mghrulefill{\RW}\rule[-1\pyy]{2\RW}{\py}\par\nobreak
}
\makeatother
''',
    'preamble': r'''
\let\emph\relax
\DeclareTextFontCommand{\emph}{\gtfamily\bfseries}
\renewcommand{\headfont}{\gtfamily\sffamily}
''',
}